FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git \
curl \
ca-certificates \
openssh-client \
&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python3.12 -m pip install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]